# Generated by Django 3.2.15 on 2022-08-19 12:08

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='validate',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('attempt', models.IntegerField(blank=1, default=0)),
                ('validate', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
