# Generated by Django 3.2.15 on 2022-08-19 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=50)),
                ('attempt', models.IntegerField()),
                ('updated_at', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
