# Generated by Django 3.2.15 on 2022-08-19 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_loginattempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempts',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loginattempts',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
