# Generated by Django 3.2.16 on 2022-10-19 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pancakeswapPredicition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.IntegerField(default=None, unique=True)),
                ('bull', models.FloatField(default=None)),
                ('bear', models.FloatField(default=None)),
                ('wallet_number', models.IntegerField(default=None)),
                ('transaction_hash', models.TextField(default='')),
                ('claimable', models.BooleanField(default=False)),
                ('claimed', models.BooleanField(default=False)),
                ('wallet_balance', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
