# Generated by Django 3.2.16 on 2022-10-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pancakeswappredicition',
            name='bet_type',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
