# Generated by Django 3.2.16 on 2022-10-19 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0002_pancakeswappredicition_bet_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='server_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('logging', models.TextField(default=None)),
                ('started_at', models.DateTimeField(default=None)),
                ('stoped_at', models.DateTimeField(default=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
