# Generated by Django 3.2.16 on 2022-10-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0003_server_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_status',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
    ]
