# Generated by Django 3.2.16 on 2022-10-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0006_logging'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='logging',
            new_name='message_logging',
        ),
    ]
