# Generated by Django 3.2.16 on 2022-10-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0007_rename_logging_message_logging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pancakeswappredicition',
            name='transaction_hash',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
