# Generated by Django 3.2.16 on 2022-10-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0008_alter_pancakeswappredicition_transaction_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pancakeswappredicition',
            name='epoch',
            field=models.IntegerField(default=None),
        ),
    ]
