# Generated by Django 3.2.16 on 2022-10-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0010_transaction_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_status',
            name='stoped_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
